### ISSUE TITLE
🐛 BUG: script[type*="json"] throws error unexpected token

### ISSUE THREAD

**Issue by SudoCat** [withastro/prettier-plugin-astro#346]
### Describe the Bug

Since updating to version 0.9.0, .astro files containing a script tag, where the type includes the word json cause prettier to throw an unexpected token error. The line and character number reported in the error do not related to the location of the issue.

Suddenly one of our files containing `ld+json` tags started throwing an error in our CI this morning after I updated the packages.

After some trial and error cutting random chunks of the file out, it turns out the smallest reproducible test case is simply creating a .astro file containing:
```
<script type="json"></script>
```

That's enough to cause it to explode. 

For some reason, if I move the `json` to a variable, and then pass a variable to the type, nothing explodes.

```
---
const type = "json"
---
<script type={type}></script> 
```

However, if the variable itself is named json, it explodes. You can have other attributes with the letters "json" on a script tag, it is only when they are inside the "type" attribute that the error presents itself.

Considering the error references babel parsing, and the nature of its occurence, I'm presuming something strange is attempting to read the script tag as a json file when it sees the word json inside the type attribute? no idea what else could be happening.

VS Code Prettier Logs:
```
["INFO" - 10:29:10] Formatting file:///Users/robinneal/Contracts/Wonderbly/frontend/apps/storefront/src/components/test.astro
["INFO" - 10:29:10] Using config file at '/Users/robinneal/Contracts/Wonderbly/frontend/.prettierrc.cjs'
["INFO" - 10:29:10] Using ignore file (if present) at /Users/robinneal/Contracts/Wonderbly/frontend/.prettierignore
["INFO" - 10:29:10] File Info:
{
  "ignored": false,
  "inferredParser": "astro"
}
["INFO" - 10:29:10] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:29:10] Prettier Options:
{
  "filepath": "/Users/robinneal/Contracts/Wonderbly/frontend/apps/storefront/src/components/test.astro",
  "parser": "astro",
  "plugins": [
    "/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier-plugin-astro@0.9.0/node_modules/prettier-plugin-astro/dist/index.js"
  ]
}
["ERROR" - 10:29:10] Error formatting document.
["ERROR" - 10:29:10] Unexpected token (1:1)
> 1 |
    | ^
SyntaxError: Unexpected token (1:1)
> 1 |
    | ^
    at p (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/parser-babel.js:22:1054)
    at d (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/parser-babel.js:22:1287)
    at Object.parse (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/parser-babel.js:29:51283)
    at Object.parse (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:7515:23)
    at textToDoc (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8478:39)
    at /Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8466:99
    at wrapParserTryCatch (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier-plugin-astro@0.9.0/node_modules/prettier-plugin-astro/src/printer/embed.ts:171:10)
    at Object.embed (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier-plugin-astro@0.9.0/node_modules/prettier-plugin-astro/src/printer/embed.ts:127:25)
    at Object.printSubtree (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8466:32)
    at callPluginPrintFunction (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8593:32)
    at mainPrintInternal (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at /Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8392:27
    at AstPath.each (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8384:11)
    at AstPath.map (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8391:14)
    at Object.print (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier-plugin-astro@0.9.0/node_modules/prettier-plugin-astro/src/printer/index.ts:79:39)
    at callPluginPrintFunction (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at printAstToDoc (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8529:18)
    at coreFormat (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8837:20)
    at formatWithCursor2 (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:9021:18)
    at /Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38183:12
    at Object.format (/Users/robinneal/Contracts/Wonderbly/frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38197:12)
    at t.default.format (/Users/robinneal/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:14756)
    at t.PrettierEditProvider.provideEdits (/Users/robinneal/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:11429)
    at z.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:47446)
["INFO" - 10:29:10] Formatting completed in 28ms.
```

### Steps to Reproduce

1. npm create astro@latest -- --template minimal
2. create an astro file inside the src folder
3. in the created file, write `<script type="json"></script>`
4. Prettier throws an unexpected token error. No errror was expected here.

**Comment by SudoCat** [comment]
Looking at 0.9.0 release notes, I imagine this is related to:

https://github.com/withastro/prettier-plugin-astro/commit/d2a2c262dea32dc936167bd7697e15289ecbea08

In our instance, we were dynamically generating the ld+json output, interpolating variables into it, and then assigning it to the script tag via `set:html`. This would explain why the error is thrown - it is caused specifically when the <script> tag has type json, but no content.

**Comment by SudoCat** [comment]
I attempted moving our json inline, which makes prettier happy, but then the `astro-eslint-parser` throws an error 🙃 

```
/Users/robinneal/Contracts/Wonderbly/frontend/apps/storefront/src/components/head/Seo.astro
  20:11  error  Parsing error: ';' expected
```

**Comment by Princesseuh** [comment]
Yeah, we added support for formatting JSON script tags in that commit. I didn't think about the fact that an empty script tag is technically invalid JSON and that it would cause an error 🤦‍♀️

**Comment by SudoCat** [comment]
haha yeah sorry, it's a weird edge case problem I've created 🙈 

I got started on a PR - I need to add some test cases still to verify it. I'm not sure this is the best technique, but in theory you don't need to format empty tags.
