### ISSUE TITLE
🐛 BUG:Plugin doesn't work fun with prettier3

### ISSUE THREAD

**Issue by Gu-Miao** [withastro/prettier-plugin-astro#354]
### Describe the Bug

I noticed that prettier 3 is comming, so I updated the package. But I found that the plugin didn't work well.

Here's the error log:

```
["ERROR" - 11:07:34] Error formatting document.
["ERROR" - 11:07:34] printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
    at printEmbeddedLanguages (file:///E:/Projects/blog/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:17963:11)
    at printAstToDoc (file:///E:/Projects/blog/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18094:9)
    at async coreFormat (file:///E:/Projects/blog/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18405:14)
    at async formatWithCursor (file:///E:/Projects/blog/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18603:14)
    at async Module.format2 (file:///E:/Projects/blog/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:21789:25)
["INFO" - 11:07:34] Formatting completed in 9ms.
```

My prettier configuration:

```cjs
module.exports = {
  arrowParens: 'avoid',
  bracketSpacing: true,
  endOfLine: 'lf',
  printWidth: 100,
  semi: false,
  tabWidth: 2,
  useTabs: false,
  singleQuote: true,
  trailingComma: 'all',
  plugins: ['prettier-plugin-astro'],
  overrides: [
    {
      files: '*.astro',
      options: {
        parser: 'astro',
      },
    },
  ],
}
```

Package versions: 
* prettier: 3.0.0
* prettier-plugin-astro: 0.10.0

### Steps to Reproduce

1. Update `prettier` to the latest version.
2. Use format on your VSCode (make sure that you have prettier plugin in your VSCode)

**Comment by David-Kyrat** [comment]
I am the same problem with  prettier@3.2.4 and prettier-svelte
