### ISSUE TITLE
🐛 BUG: JSX not formatted when following docs of this plugin

### ISSUE THREAD

**Issue by gkatsanos** [withastro/prettier-plugin-astro#367]
### Describe the Bug

the HTML/JSX below is not formatted, error in console:

```html
// Layout.astro
    {
      brand === "ep" && (
        epFavIcons.map((favicon) => (
          <link rel="icon" href={favicon.href} type={favicon.type} />
        ))
        ) || (
        wlwFavIcons.map((favicon) => (
          <link rel="icon" href={favicon.href} type={favicon.type} />
        ))
      )
    }
```

### Steps to Reproduce

```js
// .prettierrc.mjs
export default {
  trailingComma: 'es5',
  tabWidth: 2,
  semi: false,
  singleQuote: false,
  plugins: [require.resolve('prettier-plugin-astro'), 'prettier-plugin-tailwindcss'],
  overrides: [
    {
      files: '*.astro',
      options: {
        parser: 'astro'
      }
    }
  ]
}
```

```json
// vscode settings.json
{
  "files.insertFinalNewline": true,
  "editor.formatOnSave": true,
  "javascript.format.enable": false,
  "typescript.format.enable": false,
  "editor.tabSize": 2,
  "html.format.enable": false,
  "json.format.enable": false,
  "less.format.enable": false,
  "css.format.enable": false,
  "scss.format.enable": false,
  "yaml.format.enable": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "files.autoSave": "onFocusChange",
  "prettier.documentSelectors": ["**/*.astro"],
  "[astro]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

```html
// Layout.astro
    {
      brand === "ep" && (
        epFavIcons.map((favicon) => (
          <link rel="icon" href={favicon.href} type={favicon.type} />
        ))
        ) || (
        wlwFavIcons.map((favicon) => (
          <link rel="icon" href={favicon.href} type={favicon.type} />
        ))
      )
    }
```

```
// VsCode OUTPUT
["INFO" - 09:51:54] Formatting file:///Users/gkatsanos/repos/visable/requests-frontend/src/layouts/Layout.astro
["DEBUG" - 09:51:54] Local prettier module path: '/Users/gkatsanos/repos/visable/requests-frontend/node_modules/prettier/index.cjs'
["ERROR" - 09:51:54] Error resolving prettier configuration for /Users/gkatsanos/repos/visable/requests-frontend/src/layouts/Layout.astro
["ERROR" - 09:51:54] Error loading node module '/Users/gkatsanos/repos/visable/requests-frontend/node_modules/prettier/index.cjs'
Error: Error loading node module '/Users/gkatsanos/repos/visable/requests-frontend/node_modules/prettier/index.cjs'
    at t.loadNodeModule (/Users/gkatsanos/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:2848)
    at t.PrettierMainThreadInstance.import (/Users/gkatsanos/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:17760)
    at t.PrettierMainThreadInstance.resolveConfigFile (/Users/gkatsanos/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:18457)
    at t.ModuleResolver.resolveConfig (/Users/gkatsanos/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:6705)
    at t.ModuleResolver.getResolvedConfig (/Users/gkatsanos/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:7540)
    at t.default.format (/Users/gkatsanos/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:14563)
    at t.PrettierEditProvider.provideEdits (/Users/gkatsanos/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:12672)
["DEBUG" - 09:52:27] Local prettier module path: '/Users/gkatsanos/repos/visable/requests-frontend/node_modules/prettier/index.js'
["DEBUG" - 09:52:48] Local prettier module path: '/Users/gkatsanos/repos/visable/requests-frontend/node_modules/prettier/index.js'
["DEBUG" - 09:53:13] Local prettier module path: '/Users/gkatsanos/repos/visable/requests-frontend/node_modules/prettier/index.js'
```

**Comment by Princesseuh** [comment]
That error doesn't seem related to us, it seems like the Prettier VS Code extension failed to load Prettier itself.

**Comment by gkatsanos** [comment]
@Princesseuh in your readme you are referring to using `require.resolve` to load the plugin. Could you please elaborate on which prettier config file type this works for?
Running prettier directly via terminal complains for exactly this line:
```
[error] require() of ES Module /Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/prettier-plugin-astro@0.11.0/node_modules/prettier-plugin-astro/dist/index.js from /Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js not supported.
[error] Instead change the require of /Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/prettier-plugin-astro@0.11.0/node_modules/prettier-plugin-astro/dist/index.js in /Users/gkatsanos/repos/visable/requests-frontend/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by Princesseuh** [comment]
Please follow the configuration in this PR https://github.com/withastro/prettier-plugin-astro/pull/366

**Comment by gkatsanos** [comment]
I actually downgraded prettier to v2 just to avoid experimenting :) (I had already enough issues with astro+prettier). 
What would that be for v2?

**Comment by Princesseuh** [comment]
> I actually downgraded prettier to v2 just to avoid experimenting :) (I had already enough issues with astro+prettier). What would that be for v2?

For v2 it would be the current configuration and any versions of the plugin below 0.11.0

**Comment by gkatsanos** [comment]
Alright so it appears that the VSCode PRettier plugin is having issues with prettier v3 - so now if you have prettier v3 locally , it wont play nice with the prettier vscode extension. I disabled the VSCode plugin and I set the formatter to be 'Astro'.
