### ISSUE TITLE
🐛 BUG: src/pages/index.astro: Error: printer.embed has too many parameters. The API changed in Prettier v3.

### ISSUE THREAD

**Issue by Squirreljetpack** [withastro/prettier-plugin-astro#374]
### Describe the Bug

Hi, sorry I'm not very comfortable with js sorry, it may be that i have set something up incorrectly.

I ran npx create-blogster@latest --theme sleek
I installed packages with npm:
```
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.7.3",
    "@typescript-eslint/parser": "^6.7.3",
    "eslint": "^8.50.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-config-standard-with-typescript": "^39.1.0",
    "eslint-plugin-astro": "^0.29.0",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-n": "^16.1.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-promise": "^6.1.1",
    "prettier": "^3.0.3",
    "prettier-config-standard": "^7.0.0",
    "prettier-plugin-astro": "^0.7.2",
    "typescript": "^4.9.5"
  }
```
prettier.config.mjs
```
/** @type {import("prettier").Config} */
export default {
  plugins: ["prettier-plugin-astro"],
  overrides: [
    {
      files: "*.astro",
      options: {
        parser: "astro",
      },
    },
  ],
};
```
When I run "npx prettier --write "**/*.astro", i get error

```
src/pages/projects.astro
[error] src/pages/projects.astro: Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
[error]     at printEmbeddedLanguages (file:///home/archrichard/github/website_repos/my-blogster-blog/node_modules/prettier/index.mjs:17669:11)
[error]     at printAstToDoc (file:///home/archrichard/github/website_repos/my-blogster-blog/node_modules/prettier/index.mjs:17800:9)
[error]     at async coreFormat (file:///home/archrichard/github/website_repos/my-blogster-blog/node_modules/prettier/index.mjs:18111:14)
[error]     at async formatWithCursor (file:///home/archrichard/github/website_repos/my-blogster-blog/node_modules/prettier/index.mjs:18309:14)
[error]     at async formatFiles (file:///home/archrichard/github/website_repos/my-blogster-blog/node_modules/prettier/internal/cli.mjs:7082:18)
[error]     at async main (file:///home/archrichard/github/website_repos/my-blogster-blog/node_modules/prettier/internal/cli.mjs:7274:5)
[error]     at async Module.run (file:///home/archrichard/github/website_repos/my-blogster-blog/node_modules/prettier/internal/cli.mjs:7228:5)
```

Also, not sure if related but when I run eslint with this config
```
module.exports = {
  // ...
  env: {
    browser: true,
    es2021: true,
  },
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "./tsconfig.json",
    ecmaVersion: "latest",
    sourceType: "module",
  },
  extends: [
    // ...
    "plugin:astro/recommended",
  ],
  rules: {
    // "prettier/prettier": "error"
  },
  // ...
  overrides: [
    {
      // Define the configuration for `.astro` file.
      files: ["*.astro"],
      // Allows Astro components to be parsed.
      parser: "astro-eslint-parser",
      // Parse the script in `.astro` as TypeScript by adding the following configuration.
      // It's the setting you need when using TypeScript.
      parserOptions: {
        parser: "@typescript-eslint/parser",
        extraFileExtensions: [".astro"],
      },
      rules: {
        // override/add rules settings here, such as:
        // "astro/no-set-html-directive": "error"
      },
    },
    // ...
  ],
};

```
I get a bunch of `error  Definition for rule 'prettier/prettier' was not found  prettier/prettier` if I uncomment "prettier/prettier": "error"

### Steps to Reproduce

npx create-blogster@latest --theme sleek
npm install
npm i -D eslint eslint-plugin-astro @typescript-eslint/parser prettier prettier-config-standard prettier-plugin-astro
create config files as above
run `npx prettier -w "**`

**Comment by Princesseuh** [comment]
Your Astro plugin is outdated, for Prettier 3 you need to use any versions higher than 0.11.0

**Comment by Squirreljetpack** [comment]
I'm using 0.1.2

**Comment by Squirreljetpack** [comment]
Thanks I checked npm info but misread it ha.
I updated prettier-plugin-astro
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.7.3",
    "@typescript-eslint/parser": "^6.7.3",
    "eslint": "^8.50.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-config-standard-with-typescript": "^39.1.0",
    "eslint-plugin-astro": "^0.29.0",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-n": "^16.1.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-promise": "^6.1.1",
    "prettier": "^3.0.3",
    "prettier-config-standard": "^7.0.0",
    "prettier-plugin-astro": "^0.1.2",
    "typescript": "^4.9.5"
  }
}
But ruynning npx prettier --write "**/*.{js,jsx,ts,tsx,md,mdx,astro}" I still get the same error

**Comment by Princesseuh** [comment]
`"prettier-plugin-astro": "^0.1.2",`
the latest version of the plugin is `0.12.0`

**Comment by Squirreljetpack** [comment]
ah ic thank you
