### ISSUE TITLE
🐛 BUG: Broken astro file parser

### ISSUE THREAD

**Issue by vanntile** [withastro/prettier-plugin-astro#388]
### Describe the Bug

Run prettier in a project with astro files outputs the following:

```
[error] src/pages/resume.astro: Error: Unhandled node type "frontmatter"!
[error]     at Object.print (file:///home/user/src/project/node_modules/prettier-plugin-astro/dist/index.js:538:19)
[error]     at callPluginPrintFunction (file:///home/user/src/project/node_modules/prettier/index.mjs:20132:20)
[error]     at mainPrintInternal (file:///home/user/src/project/node_modules/prettier/index.mjs:20115:18)
[error]     at mainPrint (file:///home/user/src/project/node_modules/prettier/index.mjs:20098:14)
[error]     at file:///home/user/src/project/node_modules/prettier/index.mjs:19308:23
[error]     at AstPath.each (file:///home/user/src/project/node_modules/prettier/index.mjs:19295:9)
[error]     at AstPath.map (file:///home/user/src/project/node_modules/prettier/index.mjs:19307:10)
[error]     at Object.print (file:///home/user/src/project/node_modules/prettier-plugin-astro/dist/index.js:349:50)
[error]     at callPluginPrintFunction (file:///home/user/src/project/node_modules/prettier/index.mjs:20132:20)
[error]     at printAstToDoc (file:///home/user/src/project/node_modules/prettier/index.mjs:20087:22)
```

### Steps to Reproduce

1. Using the following version:
```jsonc
...
    "node": "20.9.0",
    "prettier": "^3.1.0",
    "prettier-plugin-astro": "^0.12.2",
    "prettier-plugin-tailwindcss": "^0.5.7",
...
```
2. Using the following config file
```json
{
  "plugins": ["prettier-plugin-astro", "prettier-plugin-tailwindcss"],
  "overrides": [
    {
      "files": "*.prettierrc",
      "options": {
        "parser": "json"
      }
    },
    {
      "files": "*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ],
  "embeddedLanguageFormatting": "off"
}
```
3. Run the following command
```sh
npx prettier -c --config .prettierrc "src/**/*.{astro,js,ts}"
```

**Comment by Princesseuh** [comment]
This plugin makes extensive use of embedded languages, so it isn't compatible with `embeddedLanguageFormatting: "off"` at this time.

We could make it so it doesn't throw an error though, but most of the file wouldn't get formatted.

**Comment by vanntile** [comment]
Thank you for letting me know. What I wanted can be achieved apparently by this:

```
...
    {
      "files": "*.mdx",
      "options": {
        "embeddedLanguageFormatting": "off"
      }
    }
```

This way, the inner code blocks in MDX don't get formatted and I don't get the above error for `.astro` files. Will close the issue
