### ISSUE TITLE
🐛 BUG: Incorrect ordering of elements in formatting

### ISSUE THREAD

**Issue by kdheepak** [withastro/prettier-plugin-astro#389]
### Describe the Bug

This 

```
<html lang="en">
  <Head {title} {description} />
  <Navbar />
  <body>
    <slot />
  </body>
  <Footer />
</html>
```

gets formatted to this:

```
<html lang="en">
  <Head {title} {description} />
  <Navbar />
  <body>
    <slot />
    <Footer />
  </body>
</html>
```

Worse still, if I add `<!-- prettier-ignore -->` at the top of the block, prettier crashes.

```
<!-- prettier-ignore -->
<html lang="en">
  <Head {title} {description} />
  <Navbar />
  <body>
    <slot />
  </body>
  <Footer />
</html>
```

```
[error] src/layouts/layout.astro: TypeError: Cannot read properties of undefined (reading 'offset')
[error]     at Object.locEnd (file:///Users/test/node_modules/prettier-plugin-astro/dist/index.js:799:45)
[error]     at Object.print (file:///Users/test/node_modules/prettier-plugin-astro/dist/index.js:338:50)
[error]     at callPluginPrintFunction (file:///Users/test/node_modules/prettier/index.mjs:20132:20)
[error]     at mainPrintInternal (file:///Users/test/node_modules/prettier/index.mjs:20115:18)
[error]     at mainPrint (file:///Users/test/node_modules/prettier/index.mjs:20098:14)
[error]     at file:///Users/test/node_modules/prettier/index.mjs:19308:23
[error]     at AstPath.each (file:///Users/test/node_modules/prettier/index.mjs:19295:9)
[error]     at AstPath.map (file:///Users/test/node_modules/prettier/index.mjs:19307:10)
```

### Steps to Reproduce

Add the code about to `./src/layouts/layout.astro` and save in VSCode. Here's my `.prettierrc` file for reference

```
{
  "useTabs": false,
  "quoteProps": "preserve",
  "singleQuote": false,
  "trailingComma": "all",
  "printWidth": 100,
  "tabWidth": 2,
  "bracketSameLine": false,
  "bracketSpacing": true,
  "proseWrap": "always",
  "plugins": ["prettier-plugin-astro", "prettier-plugin-tailwindcss", "prettier-plugin-svelte"]
}
```

**Comment by Princesseuh** [comment]
What's the content of Footer? Having elements after body but still in html is quite unusual

**Comment by kdheepak** [comment]
The content of footer is just a regular footer (e.g. like the one here on GitHub).

I guess I'm learning that footer should be part of the body, so prettier is doing the right thing here. I'll close this issue!

**Comment by luchillo17** [comment]
@kdheepak Afaik the only thing outside of the `body` you should have is the `head` with the meta tags, be it CSS, js, style tags, or script tags, it goes either in the `head` or the `body`.

I'm impressed Prettier actually moved the footer up, but I would expect it to also move the navbar down...
